name: On Push
on:
  push:
env:
  IMAGE: ghcr.io/rogueoneecho/caddy-cloudflare
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:

  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - id: release
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: ${{ secrets.RELEASE_SCRIPT }}

    - run: echo "# ${{ steps.release.outputs.version}}" >> $GITHUB_STEP_SUMMARY

    - run: cat /tmp/RELEASE-NOTES.md >> $GITHUB_STEP_SUMMARY

  build:
    if: needs.release.outputs.version != ''
    strategy:
      matrix:
        include:
        - runner: ubuntu-24.04
          arch: amd
        - runner: ubuntu-24.04-arm
          arch: arm
    runs-on: ${{ matrix.runner }}
    needs:
    - release
    steps:

    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ matrix.arch }}-${{ github.sha }}
        restore-keys: |
          buildx-${{ matrix.arch }}-

    - run: echo $GH_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: docker buildx create --use

    - run: >
        docker buildx build src
        --platform "linux/${{ matrix.arch }}64"
        --build-arg VERSION=${{ needs.release.outputs.version }}
        --tag ${{ env.IMAGE }}:${{ needs.release.outputs.version }}-${{ matrix.arch }}
        --cache-from=type=local,src=/tmp/.buildx-cache
        --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max
        --provenance false
        --push

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - run: rm -rf /tmp/.buildx-cache
    - run: mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  push:
    runs-on: ubuntu-24.04
    needs:
    - release
    - build
    steps:

    - run: echo $GH_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: >
        docker manifest create ${{ env.IMAGE }}:${{ needs.release.outputs.version }}
        ${{ env.IMAGE }}:${{ needs.release.outputs.version }}-amd
        ${{ env.IMAGE }}:${{ needs.release.outputs.version }}-arm

    - run: docker manifest push ${{ env.IMAGE }}:${{ needs.release.outputs.version }}

    - if: github.ref_name == 'alpha'
      run: >
        docker manifest create ${{ env.IMAGE }}:${{ github.ref_name }}
        ${{ env.IMAGE }}:${{ needs.release.outputs.version }}-amd
        ${{ env.IMAGE }}:${{ needs.release.outputs.version }}-arm

    - if: github.ref_name == 'alpha'
      run: docker manifest push ${{ env.IMAGE }}:${{ github.ref_name }}

    - if: contains(needs.release.outputs.version, '-') == false
      run: >
        docker manifest create ${{ env.IMAGE }}:latest
        ${{ env.IMAGE }}:${{ needs.release.outputs.version }}-amd
        ${{ env.IMAGE }}:${{ needs.release.outputs.version }}-arm

    - if: contains(needs.release.outputs.version, '-') == false
      run: docker manifest push ${{ env.IMAGE }}:latest

